## Configuration for the from_cellranger Snakemake workflow.

# sample name, pointing to cellranger count output directory (same as the ""--id" input for cellranger count)
Samples:
    C2Cnuc_yPAP1:
    C2Cnuc_ctrl1:
    SKMA:
    SRMB:

CR_REF: /workdir/dwm269/genomes/mm39_all/GRCm39_cellranger_GENCODE_M27 #DWM - directory containing cellranger count reference

DATADIR: /workdir/dwm269/totalRNA/data/cr_count/GRCm39_GENOCODEM27 # directory where cellranger_count outputs are stored - be sure to use an absolute path (starting with root)
TMPDIR: ./tmp # directory for temporary files

########################################################################################################
# Executables - file paths
########################################################################################################
PICARD: /home/dwm269/miniconda3/envs/scTAR1.2/share/picard-2.18.29-0/picard.jar
DROPSEQ: /home/dwm269/miniconda3/envs/scTAR1.2/share/dropseq_tools-2.4.0-1
GTFTOGENEPRED: /home/dwm269/miniconda3/envs/scTAR1.2/bin/gtfToGenePred # used to convert gtf to reFflat format, not needed if annotation is in reFflat
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

CORES: 20 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")

MERGEBP: 500
THRESH: 1000000
