## Configuration for the from_cellranger Snakemake workflow.

# sample name, pointing to cellranger count output directory (same as the ""--id" input for cellranger count)
Samples:
    oprescu_D5_cellranger_count:
    muscle_d_cellranger_count:
    # snRNA-seq_Tibialis_cellranger_count:

CR_REF: /workdir/dwm269/genomes/mm10_all/mm10_cellranger #DWM - directory containing cellranger count reference

DATADIR: /workdir/dwm269/totalRNA/data # directory where cellranger_count outputs are stored - be sure to use an absolute path (starting with root)
MERGEDOUTDIR: /workdir/dwm269/totalRNA/data/MULTI_CR_TEST_DIR
TMPDIR: ./tmp # directory for temporary files

########################################################################################################
# Executables - file paths
########################################################################################################
PICARD: /home/dwm269/miniconda3/envs/scTAR1.2/share/picard-2.18.29-0 /picard.jar
DROPSEQ: /home/dwm269/miniconda3/envs/scTAR1.2/share/dropseq_tools-2.4.0-1
GTFTOGENEPRED: /home/dwm269/miniconda3/envs/scTAR1.2/bin/gtfToGenePred # used to convert gtf to reFflat format, not needed if annotation is in reFflat
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

CORES: 15 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")

MERGEBP: 500
THRESH: 10000000
